//creat a const variable kelvin and storing its value
const kelvin =0;
//create a var celsius that converts k to c
var celsius = kelvin-273;
//create a  var fahrenheit that converts k to f 
var fahrenheit=celsius * (9/5)+32;
//to round down the temp in f
fahrenheit=Math.floor(fahrenheit);
console.log(`The temperature is ${fahrenheit} degrees Fahrenheit.`);
var newton=celsius *(33/100);
newton=Math.floor(newton);
console.log(`The temperature is ${newton} degrees Newton.`);
